### ISSUE TITLE
Missing parameter

### ISSUE THREAD

**Issue by lamatat** [junaid04/PayFortExample#1]
Hi,

Thank you so much for this sample project ..
i have multiple questions if i may..
1. which version of payfort you are using?
2. when i tried to run it .. i will get this as response:

["language": Optional("en"), "service_command": Optional("SDK_TOKEN"), "access_code": Optional("CycHZxVj"), "merchant_identifier": Optional("zx0IPmPy5jp1vAz8Kpg7"), "device_id": Optional("0BFE841C-E978-47D1-8515-CF3063786EBD"), "signature": Optional("455841e858e9351361fe1025a411cf7763a8d4003528f14d392e38743c6840b1")]
responseString = Optional("{\"response_code\":\"00009\",\"service_command\":\"SDK_TOKEN\",\"device_id\":\"0BFE841C-E978-47D1-8515-CF3063786EBD\",\"response_message\":\"Invalid merchant identifier\",\"merchant_identifier\":\"zx0IPmPy5jp1vAz8Kpg7\",\"access_code\":\"CycHZxVj\",\"language\":\"en\",\"status\":\"00\"}")
{
    amount = 1000;
    command = PURCHASE;
    currency = SAR;
    "customer_email" = "customer@domain.com";
    language = en;
    "merchant_reference" = "XYZ9239-yu898";
}
faild
requestDic = Optional([AnyHashable("language"): en, AnyHashable("customer_email"): customer@domain.com, AnyHashable("merchant_reference"): XYZ9239-yu898, AnyHashable("amount"): 1000, AnyHashable("command"): PURCHASE, AnyHashable("currency"): SAR])
responeDic = Optional([AnyHashable("response_code"): 00001, AnyHashable("status"): 00, AnyHashable("currency"): SAR, AnyHashable("merchant_reference"): XYZ9239-yu898, AnyHashable("response_message"): Missing parameter, AnyHashable("language"): en, AnyHashable("amount"): 1000, AnyHashable("customer_email"): customer@domain.com, AnyHashable("command"): PURCHASE])
message = Optional("Missing parameter")

and i don't know which parameter is missing?!

thanks in advance :)

**Comment by junaid04** [comment]
Hi,
i have used 1.7 fortpay sdkversion
i think you have merchant identifier issue you have wrong merchant identifier see response message
"response_message":"Invalid merchant identifier"
First insert valid merchant identifier.

**Comment by lamatat** [comment]
but i have used the same merchant identifier in their document found here: https://docs.payfort.com/pdf/FORT_Mobile-SDK_iOS_Integration_Guide_v_2.8.pdf

the ones in section 4.4.2 .. isn't it for testing?

**Comment by junaid04** [comment]
i don't know but i have tried with my merchant id and access code it works fine

**Comment by junaid04** [comment]
because of invalid merchant identifier api didn't return sdk_token that's why you are getting Missing parameter message
